[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = "chase/vim-ansible-yaml"

[[plugins]]
repo = "stephpy/vim-yaml"

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'sheerun/vim-polyglot'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'rking/ag.vim'

[[plugins]]
repo = 'justinmk/vim-dirvish'

[[plugins]]
repo = 'bkad/CamelCaseMotion'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'vim-scripts/closetag.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
