"----------------------------------------
" nocompatible
"----------------------------------------

set nocompatible

"----------------------------------------
" neobundle
"----------------------------------------

filetype off

if has('vim_starting')
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/.vim/bundle/'))

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/vimproc', {
      \ 'build' : {
      \     'windows' : 'make -f make_mingw32.mak',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'unix' : 'make -f make_unix.mak',
      \    },
      \ }

NeoBundle 'Shougo/vimshell'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'Shougo/neocomplete.vim'
NeoBundle 'altercation/vim-colors-solarized'
NeoBundle 'tpope/vim-surround'
NeoBundle 'wavded/vim-stylus'
NeoBundle 'scrooloose/nerdtree'

if executable('go')
	NeoBundle 'go', {'type' : 'nosync'}
	NeoBundle 'nsf/gocode'
endif

filetype plugin indent on
NeoBundleCheck

"----------------------------------------
" go
"----------------------------------------

" auto format when the file saved
autocmd FileType go autocmd BufWritePre <buffer> Fmt

" http://yuroyoro.hatenablog.com/entry/2014/08/12/144157
autocmd FileType go :highlight goErr ctermfg=210
autocmd FileType go :match goErr /\<err\>/

"----------------------------------------
" neocomplete.vim
"----------------------------------------

" https://github.com/Shougo/neocomplete.vim
source ~/.vimrc_neocomplete

" ---------------------------------------
" syntax color
" ---------------------------------------

set t_Co=256
syntax on 
let g:solarized_termcolors=256

" I use xterm-256color as my terminfo on tmux 1.7 & Terminal.app on OS X Lion, so enable termtrans by manually.
" see https://github.com/altercation/vim-colors-solarized
let g:solarized_termtrans=1

set background=dark
colorscheme solarized

"----------------------------------------
" display
"----------------------------------------

set scrolloff=10
set laststatus=2
set statusline=%<%f\ %m%r%h%w%{'['.(&fenc!=''?&fenc:&enc).']['.&ff.']'}%=%l,%c%V%8P
set notitle
" set cursorline " <-- this makes cursor slow
" set number

"----------------------------------------
" tab
"----------------------------------------

" set expandtab
set tabstop=4
set softtabstop=0
set shiftwidth=4
set smarttab
set shiftround
set nowrap

"----------------------------------------
" edit
"----------------------------------------

set whichwrap=b,s,h,l,<,>,[,]
set autoindent
set smartindent
set backspace=indent,eol,start
"set showmatch
let loaded_matchparen = 1
vnoremap < <gv
vnoremap > >gv

"----------------------------------------
" search
"----------------------------------------

set hlsearch
nmap <Esc><Esc> :nohlsearch<CR><Esc>
set incsearch
set ignorecase
set wrapscan
set smartcase

"----------------------------------------
" backup
"----------------------------------------

set backup
set backupdir=~/.vim_tmp
set swapfile
set directory=~/.vim_tmp

"----------------------------------------
" encoding
"----------------------------------------

set termencoding=utf-8
set encoding=utf-8

"----------------------------------------
" tab editing
"----------------------------------------

nnoremap s <Nop>
nnoremap sq :<C-u>q<CR>
nnoremap sw :<C-u>wq<CR>
nnoremap st :<C-u>tabnew<CR>
nnoremap sT :<C-u>Unite tab<CR>
nnoremap sn gt
nnoremap sp gT

"----------------------------------------
" some utils
"----------------------------------------

nnoremap ; :
inoremap jk <esc>
nnoremap Q <Nop>
nnoremap ZZ <Nop>
nnoremap ZQ <Nop>
let mapleader = ","
nnoremap <Leader>vv :<C-u>VimShell<CR>


